apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: flask
        image: saurabhh45/flask-demo:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
